### ISSUE TITLE
Logo proposal

### ISSUE THREAD

**Issue by psikoz** [fiahfy/hosty#51]
Hey @fiahfy . I designed a logo for you. WDYT the logo? I designed a logo that reminds me of the electron because this project is electron based.

![hosty](https://user-images.githubusercontent.com/40601249/43136843-900d41a0-8f52-11e8-9014-6fbd6c7751b8.jpg)

**Comment by psikoz** [comment]
What do you think?

**Comment by fiahfy** [comment]
About logo, I will create it myself if necessary.
Thanks for your suggestion.
