### ISSUE TITLE
macOS Cataline 10.15.7 にてhostyが起動しなくなってしまいました。

### ISSUE THREAD

**Issue by keijiro-okamura** [fiahfy/hosty#79]
便利に使わせていただいていたので、とても悲しいです。

![スクリーンショット 2021-03-24 14 26 12](https://user-images.githubusercontent.com/50390475/112260263-ed64c580-8cac-11eb-8d00-c95a9fe6bbe4.png)

![スクリーンショット 2021-03-24 12 50 36](https://user-images.githubusercontent.com/50390475/112253137-737b0f00-8ca1-11eb-83ff-2118af232b71.png)

あと、/etc/host これまでに登録したhostたちがどこを見れば確認できるか教えていただけると幸いです。

**Comment by keijiro-okamura** [comment]
証明書などの期限切れに起因するものなのかと思っています。

https://developer.apple.com/forums/thread/130919

https://stackoverflow.com/questions/43511045/app-can-not-be-opened-because-it-is-from-an-unidentified-developer

**Comment by fiahfy** [comment]
同じOS, versionみたいですが普通に起動しますね...
一度削除して、再度 dmgから install してみてもらえますか?

データはここの保存されています（local storage）
```
 ~/Library/Application\ Support/Hosty/Local\ Storage/leveldb/
```

**Comment by keijiro-okamura** [comment]
迅速なご回答ありがとうございます。

こちら、あれから色々と原因を探してみましたところ、
こちら自分のPCに入っている他のセキュリティ系のソフトウェアが起動を阻害している可能性が高く、、
バージョンの問題やこちらのソースコードの問題ではないようです。

現に同じバージョンで動作が確認できているということで。
こちらの内容は閉じさせていただきます。
hostの保管場所についてもお答えいただきありがとうございました。とても助かります。

お手数をおかけいたしました。:bow:
ありがとうございました。
